MqttServer:
  Listeners:
    - Id: Mqtt
      Port: 1883
      Host: 0.0.0.0
      MaxMessageSizeKb: 8192
      #Username: demo
      #Password: demo
      LogLevel: INFO # ALL | INFO

    - Id: MqttWs
      Port: 1884
      Host: 0.0.0.0
      Websocket: true
      MaxMessageSizeKb: 8192
      #Username: demo
      #Password: demo
      LogLevel: INFO # ALL | INFO

GraphQLServer:
  Listeners:
    - Port: 4000
      LogLevel: INFO
      GraphiQL: true
      WriteSchemaToFile: false
      Schemas:
        - System: scada
        - System: demo1             
        - System: demo2             
#        - System: ignition
#        - System: unified
#          FieldName: DisplayName
#          RootNodes:
#            - "ns=1;s=2|Tags"

OpcUaClient:
  - Id: "scada"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:4840/server"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0    

  - Id: "demo1"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62540/server"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "demo2"
    Enabled: true
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62541"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "ignition"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://192.168.1.3:62550/discovery"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0
    UsernameProvider:
      Username: opcuauser
      Password: password

  - Id: "winccoa"
    Enabled: false
    LogLevel: INFO
    EndpointUrl: "opc.tcp://centos1.rocworks.local:4840"
    UpdateEndpointUrl: true
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
    KeepAliveFailuresAllowed: 0
    SubscriptionSamplingInterval: 0.0

  - Id: "winccua"
    Enabled: false
    LogLevel: INFO
    EndpointUrl:  "opc.tcp://DESKTOP-60VI6G8.rocworks.local:4890"
    SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
    SubscriptionSamplingInterval: 0
    UsernameProvider:
      Username: username1
      Password: password1
    WriteParameters:
      QueueSize: 1000
      BlockSize: 100
      WithTime: true
    MonitoringParameters:
      BufferSize: 10
      SamplingInterval: 0.0
      DiscardOldest: true


Database:
  Logger:
    - Id: kafka
      Type: Kafka
      Enabled: true
      LogLevel: INFO
      Servers: linux0.rocworks.local:9092
      Configs:
        batch.size: 25000
        group.id: frankenstein-producer
        enable.auto.commit: true
        auto.commit.interval.ms: 1000
      WriteParameters:
        QueueSize: 10000
        BlockSize: 1000
      TopicName: opcua
      Logging:
        - Topic: opc/scada/path/Objects/Home/#
        - Topic: opc/demo1/path/Objects/Variables/#
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/#

    - Id: influx1
      Type: InfluxDB
      Enabled: false
      Url: http://nuc1.rocworks.local:8087
      Database: test
      Username: ""
      Password: ""
      WriteParameters:
        QueueSize: 20000
        BlockSize: 10000
      Logging:
        - Topic: opc/demo1/path/ns=2;s=Variables\/Int32/+
        - Topic: opc/unified/node/ns=1;s=2.199.1.0.0.0
        - Topic: opc/unified/node/ns=1;s=2.200.1.0.0.0
        - Topic: opc/unified/node/ns=1;s=2.253.1.0.0.0
        - Topic: opc/unified/node/ns=1;s=2.252.1.0.0.0
        - Topic: opc/unified/node/ns=1;s=2.251.1.0.0.0
        - Topic: opc/unified/node/ns=1;s=2.248.1.0.0.0
        - Topic: opc/unified/node/ns=1;s=2.246.1.0.0.0
        - Topic: opc/unified/node/ns=1;s=2.245.1.0.0.0

    - Id: iotdb1
      Type: IoTDB
      Enabled: false
      Host: nuc1.rocworks.local
      Port: 6667
      Database: root.test
      Username: root
      Password: root
      WriteDetails: false
      WriteParameters:
        QueueSize: 20000
        BlockSize: 10000
      Logging:
        - Topic: mqtt/rpi/path/Meter_Input/+
        - Topic: mqtt/rpi/path/Meter_Output/+
        - Topic: mqtt/rpi/path/PV/Spot/+

    - Id: pgsql1
      Type: Jdbc
      Enabled: false
      Url: jdbc:postgresql://nuc1.rocworks.local:5432/scada
      Username: system
      Password: manager
      Logging:
        - Topic: mqtt/rpi/path/Meter_Input/+
        - Topic: mqtt/rpi/path/Meter_Output/+
        - Topic: mqtt/rpi/path/PV/Spot/+

    - Id: kafka1
      Type: Kafka
      Enabled: false
      Servers: nuc1.rocworks.local:9092
      WriteParameters:
        QueueSize: 20000
        BlockSize: 10000
      Logging:
        - Topic: mqtt/rpi/path/Meter_Input/+
        - Topic: mqtt/rpi/path/Meter_Output/+
        - Topic: mqtt/rpi/path/PV/Spot/+

